apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete-app
  labels:
    app: svc-lanchonete-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: pod-lanchonete-app