spring:
  application:
    name: ${APP_NAME:lanchonete}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}
  datasource:
    url: ${URL_DATABASE:jdbc:mysql://mysql-db:3306/produto}
    username: ${USER_DATABASE:user}
    password: ${PASSWORD_DATABASE:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${APP_PORT:8080}
