name: Cria o PR para a release

on:
  push:
    branches:
      - develop

jobs:
  pr-to-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Configure Git
        run: |
          git config --global user.email "gtbarbosa@live.com"
          git config --global user.name "gustavo-dev"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verificar se já existe PR aberto para release
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base release --head $(echo "${{ github.ref }}" | sed 's/refs\/heads\///') --json url --jq 'length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.PR_EXISTS == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          gh pr create --base release --head $BRANCH_NAME --title "PR da branch: $BRANCH_NAME para a branch release" --body "PR criado automaticamente. From $BRANCH_NAME to release."
